### PR TITLE
Add passing of args and kwargs to Model.

### PR DESCRIPTION
**Pull request by hgaiser**
This allows to use args from Model (such as `name`).

### CODE REVIEW

**Comment by hgaiser** [comment]
Okay this PR grew a bit more than I thought :)

It now does:

- Pass `args` and `kwargs` to model.
- Change `ResNet` classes to functions returning `Model` (there wasn't really a reason for it to be a subclass?).
- Update the `TimeDistributed` version of `ResNet` to include the changes from https://github.com/broadinstitute/keras-resnet/pull/24 . (are these even used?)

**Comment by 0x00b1** [comment]
Thanks, @hgaiser. I'll take a look today.

> Update the TimeDistributed version of ResNet to include the changes from #24 . (are these even used?)

The names are used for loading weights by name.

**Comment by hgaiser** [comment]
I meant are the time distributed versions of ResNet even used :)

I know the blocks are used in keras-rcnn, but the ResNet model?

**Comment by 0x00b1** [comment]
Oops! I misread.

The TimeDistributed model is used for video classification. It can also be used for volumetric classification (if, for some reason, you’re dealing with volumes that have an irregular number of slices). However, it’s still wonky. 😜 It’d be nice if TimeDistributed could wrap entire models so we didn’t need to provide this implementation.

**Comment by hgaiser** [comment]
Ah oke, so they do serve a purpose :) good to know

**Comment by 0x00b1** [comment]
@hgaiser I want to merge this soon! Would you mind rebasing and removing the whitespace changes?

**Comment by hgaiser** [comment]
> @hgaiser I want to merge this soon! Would you mind rebasing and removing the whitespace changes?

Done! The whitespace changes are intentional though, since it is no longer a class it has 'dedented' (correct word for that?).

**Comment by hgaiser** [comment]
@0x00b1 or @jhung0 can this be merged?

**Comment by hgaiser** [comment]
Can be closed since https://github.com/broadinstitute/keras-resnet/pull/27 got merged.

**Comment by 0x00b1** [comment]
Thanks, @hgaiser. I was just about to ask. 😎

**Pull request closed without merging**
